import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.pro.bg,
    },
    header: {
        backgroundColor: Colors.pro.header,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 14,
    },
    backBtn: {
        padding: 4,
    },
    headerTitle: {
        color: Colors.white,
        fontSize: 18,
        fontWeight: '700',
    },
    assignedBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(34,197,94,0.18)',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        gap: 6,
    },
    greenDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: Colors.pro.accent,
    },
    assignedBadgeText: {
        color: Colors.pro.accent,
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    cancelledBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(239,68,68,0.18)',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        gap: 6,
    },
    redDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#EF4444',
    },
    cancelledBadgeText: {
        color: '#EF4444',
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    content: {
        padding: 16,
        gap: 16,
    },
    alertSuccess: {
        backgroundColor: 'rgba(34,197,94,0.12)',
        borderWidth: 1,
        borderColor: 'rgba(34,197,94,0.3)',
        borderRadius: 12,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
    },
    alertSuccessTitle: {
        color: Colors.white,
        fontSize: 15,
        fontWeight: '700',
    },
    alertSuccessSub: {
        color: Colors.neutral[300],
        fontSize: 13,
        marginTop: 2,
    },
    alertCancelled: {
        backgroundColor: 'rgba(239,68,68,0.12)',
        borderWidth: 1,
        borderColor: 'rgba(239,68,68,0.3)',
        borderRadius: 12,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
    },
    alertCancelledTitle: {
        color: Colors.white,
        fontSize: 15,
        fontWeight: '700',
    },
    alertCancelledSub: {
        color: Colors.neutral[300],
        fontSize: 13,
        marginTop: 2,
    },
    customerCard: {
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 14,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        gap: 12,
    },
    sectionHeading: {
        color: Colors.neutral[400],
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    customerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
    },
    customerAvatar: {
        width: 52,
        height: 52,
        borderRadius: 26,
    },
    customerAvatarPlaceholder: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: Colors.pro.accentDim,
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarInitials: {
        color: Colors.white,
        fontSize: 18,
        fontWeight: '700',
    },
    customerInfo: {
        flex: 1,
        gap: 4,
    },
    customerName: {
        color: Colors.white,
        fontSize: 17,
        fontWeight: '700',
    },
    ratingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    ratingText: {
        color: Colors.neutral[300],
        fontSize: 13,
        fontWeight: '600',
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 2,
    },
    locationText: {
        color: Colors.neutral[400],
        fontSize: 12,
        flex: 1,
    },
    contactButtonsRow: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 4,
    },
    contactBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 10,
        gap: 8,
    },
    whatsappBtn: {
        backgroundColor: '#25D366',
    },
    callBtn: {
        backgroundColor: '#3B82F6',
    },
    chatBtn: {
        backgroundColor: '#059669',
    },
    contactBtnText: {
        color: Colors.white,
        fontSize: 12,
        fontWeight: '700',
    },
    jobCard: {
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 14,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        gap: 12,
    },
    jobHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: 8,
    },
    jobTitle: {
        flex: 1,
        color: Colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
    categoryBadge: {
        backgroundColor: 'rgba(255,255,255,0.08)',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 6,
    },
    categoryBadgeText: {
        color: Colors.neutral[300],
        fontSize: 11,
        fontWeight: '600',
    },
    budgetBox: {
        backgroundColor: 'rgba(34,197,94,0.08)',
        padding: 12,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    budgetLabel: {
        color: Colors.neutral[300],
        fontSize: 13,
    },
    budgetValue: {
        color: Colors.pro.accent,
        fontSize: 18,
        fontWeight: '700',
    },
    descBox: {
        gap: 4,
    },
    descLabel: {
        color: Colors.neutral[400],
        fontSize: 12,
        fontWeight: '600',
    },
    descText: {
        color: Colors.neutral[300],
        fontSize: 13,
        lineHeight: 18,
    },
    completeBtn: {
        backgroundColor: Colors.pro.accent,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 12,
        gap: 8,
        marginTop: 8,
    },
    completeBtnText: {
        color: Colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
    returnBtn: {
        backgroundColor: '#374151',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 12,
        marginTop: 8,
    },
    tapToViewReviewsHint: {
        fontSize: 11,
        color: Colors.pro.accent,
        fontWeight: '600',
        marginTop: 2,
        marginBottom: 6,
    },
    skeletonContainer: {
        gap: 12,
    },
    errorContainer: {
        alignItems: 'center',
        paddingVertical: 12,
        gap: 10,
    },
    errorRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    errorText: {
        color: Colors.neutral[300],
        fontSize: 13,
    },
    retryBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: Colors.pro.accentDim,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
    },
    retryBtnText: {
        color: Colors.white,
        fontSize: 13,
        fontWeight: '600',
    },
});
